name: get_news_yesterday_data-science.yml
on:
  push:
    branches: main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo
      - uses: actions/checkout@v4

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install R packages
      - uses: r-lib/actions/setup-renv@v2

      # Install pandoc
      - uses: r-lib/actions/setup-pandoc@v2

      # Render the rmarkdown file into rmd/
      - name: Render Rmarkdown
        run: Rscript R/get_news_yesterday_data-science.R
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY}}

      # Automatically commit results
      - uses: stefanzweifel/git-auto-commit-action@v5
